Feature/initialize
devSongStudy/VillageBoard pull request #1
Opened 2020-11-22 12:54 UTC by devSongStudy

프로젝트 기본 셋팅
- Firebase 
- 화면 플로우

2020-11-22 14:30 UTC, deviankim requested changes

2020-11-22 14:30 UTC, deviankim commented on android/app/build.gradle
> +        multiDexEnabled true
flutter 하고난 이후로는 안드로이드 라이브러리를 많이 안써서 multiDex 안켜주어도 되지 않을까 생각하고 있었습니다.
혹시 켜줘야 하는 상황이 된건가요?

2020-11-23 02:17 UTC, devSongStudy commented on android/app/build.gradle
> +        multiDexEnabled true
firebaseflutter.dev 문서상에 있어서 넣었습니다.  ^^;

2020-11-23 03:14 UTC, deviankim approved these changes

2020-11-23 22:33 UTC, closed without merging